---

- name: Make Homebrew Directroy
  become: yes
  file:
    path: /opt/homebrew
    state: directory
    owner: "{{ local_user_name }}"
    group: wheel
    mode: 0755
  register: homebrew_directory

- name: Install Homebrew
  shell: curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C homebrew
  register: homebrew_install

- name: Through path of homebrew
  command: echo 'export PATH=/opt/homebrew/bin:$PATH' >> .zshrc

- name: Reload zshrc
  command: source ~/.zshrc

- name: Check brew command
  command: brew -v

- name: upgrade homebrew
  command: brew upgrade

- name: Install packages
  homebrew:
    name: "{{ item }}"
    state: present
  ignore_errors: true
  loop:
    - awscli
    - ansible-lint
    - rbenv
    - nodenv
    - git
    - rust
    - golang
    - openssl
    - libffi
    - mysql
    - tig
    - tfenv
    - python3
    - docker
    - zsh-syntax-highlighting
    - yarn
    - zstd

- name: Install terraform from build source
  homebrew:
    name: terraform
    install_options: build-from-source
    state: present
