---

# 2020/12/05現在、M1チップでのcask installはエラーが出るので無視する
- name: Install homebrew cask
  homebrew:
    name: cask
    state: present
  ignore_errors: yes

- name: Install packages
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: "installed"
    install_options: "appdir=/Applications"
  loop:
    - google-chrome
    - slack
    - 1password
    - zoom
    - rubymine
    - intellij-idea
    - pycharm
    - webstorm
    - kindle
    - alfred
    - miro
    - dropbox
    - onedrive
    - visual-studio-code
    - skitch
    - adobe-acrobat-pro
    - postman
    - discord
    - docker
    - deepl
    - notion
    - stoplight-studio
    - chatwork
    - virtualbox
